name: deploy hexo to qiniu
on: 
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
        path: main
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - uses: Hanlin-Dong/hexo-to-qiniu-action@v1
      with:
        bucket: hexo-01
        access-key: ${{ secrets.QINIU_ACCESS_KEY }}
        secret-key: ${{ secrets.QINIU_SECRET_KEY }}
        base-folder: ""
        domain: "https://note.noel.ga"
        sub-domain: ""