name: deploy hexo to qiniu
on: 
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
        path: master
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - uses: Hanlin-Dong/hexo-to-qiniu-action@v1
      with:
        bucket: hexo-01
        access-key: ${{ secrets.QINIU_ACCESS_KEY }}
        secret-key: ${{ secrets.QINIU_SECRET_KEY }}
        base-folder: ""
        domain: "https://note.noel.ga"
        sub-domain: ""
    - name: upload qiniu
      env:
        QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
        QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
        QINIU_BUCKET: ${{ secrets.QINIU_BUCKET }}
        QINIU_USER_NAME: ${{ secrets.QINIU_USER_NAME }}
      run: |
        npm install hexo-cli -g
        npm install
        hexo clean
        hexo g
        cd qiniu_upload && sh qiniu-sysc.sh
        